theme: jekyll-theme-slate
title: Chris Vetter
description: Full Stack Software Developer with experience designing and building web applications with Ruby on Rails / Node.js / PHP / AngularJS / Vue.js.